### ISSUE TITLE
这几天获取Clash配置文件一直有点问题

### ISSUE THREAD

**Issue by lhw828** [WilliamStar007/ClashX-V2Ray-TopFreeProxy#6]
最开始是发现手机端，无法正确获取.yaml配置文件，切换到电脑端出现这个提示：

illegal map value

如图：

![微信图片_20231220093248](https://github.com/WilliamStar007/ClashX-V2Ray-TopFreeProxy/assets/1897722/ca3f3855-5f0b-4035-9dee-de23372d1037)

不知道是个例还是我的客户端有问题。

操作系统：Windows 11 
梯子软件：NekoRay

**Comment by WilliamStar007** [comment]
最近有些繁忙，这个问题还存在吗？

**Comment by lhw828** [comment]
已经没有这个提示了。谢谢!
